<a href="https://colab.research.google.com/github/keenalise/Foundation-AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
a=np.array([1, 3, 4, 10, 12])
a

array([ 1,  3,  4, 10, 12])

In [10]:
a[2]=10

In [11]:
a

array([ 1,  3, 10, 10, 12])

In [12]:
np.arrange(3, 10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [13]:
np.arrange(3,12)

AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.linspace(0, 100, 11) # crestes arrays with evenly spaced numbers within  a specific

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
## multidimensional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
n=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
n[0,1]=30

In [25]:
n

array([[ 1, 30,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n2=[1,1,1]

In [27]:
n

array([[ 1, 30,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
n2

[1, 1, 1]

In [29]:
n[2]=[1, 1, 1]

In [30]:
n

array([[ 1, 30,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [31]:
n[:,2]=[0, 1, 2]

In [32]:
n

array([[ 1, 30,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

Randomly generated arrays

In [35]:
## randomly generated arrays

In [36]:
np.random(2)

TypeError: 'module' object is not callable

In [37]:
np.random.seed(2)

In [41]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [42]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [45]:
np.random.seed(1)
np.random.randn(5,2)

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038]])

Elementwise You can perform operation on entire arrays element by element


In [46]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
b=(10 + (a*2))

In [48]:
b

array([10, 12, 14, 16, 18])

Comparison Operation element wise comparisons and create boolean arrays

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a>=2

array([False, False,  True,  True,  True])

In [51]:
b

array([10, 12, 14, 16, 18])

In [52]:
a>b

array([False, False, False, False, False])

Summarize
numpy providrs functions for summarizing array data.


In [53]:
a.std()

1.4142135623730951

In [54]:
a.min()

0

In [55]:
a.max()

4

In [56]:
a.sum()

10